#server port
server:
  port: 8122

#data source
spring:
  datasource:
    url: ${ucs.datasource.dev.url}
    username: ${ucs.datasource.dev.username}
    password: ${ucs.datasource.dev.password}
  mail:
    host: smtp.exmail.qq.com #smtp.qq.com
    username: dev@linose.com
    password: Lns12345
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            socketFactory:
            fallback: false
            class: com.fintech.modules.base.util.mail.MailSSLSocketFactory
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#SMS
sms:
  url: https://api.rtc.huaweicloud.com:10443/sms/batchSendSms/v1
  appKey: JiL9xzHghaStEJAEUbB6J08hC660
  appSecret: JD0913d8GqI93zr2ZS8hv2NF4Kz5
  sender: 881905205853
  templateId: ba2b667bc714465e89a207909a4f28d5
  signature: 莱诺斯科技
  receiver: +86
  statusCallBack:

#自定义邮件主题
sendEmail:
  title: 工业测试云

#自定义头像上传路径
headimg:
  uploadPath: /usr/share/nginx/html/ucs/ftpuser
  #头像访问地址
  readPath: http://dev_ucs.iitplat.com/ftpuser/
